#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Uwe Jugel
# SPDX-License-Identifier: AGPL-3.0-or-later

import os

FILES_TO_PACK = [
    "sprite_view/utils.py",
    "sprite_view/settings.py",
    "sprite_view/logo.py",
    "sprite_view/ui/about.py",
    "sprite_view/ui/settings.py",
    "sprite_view/ui/preview.py",
    "sprite_view.py"
]

OUTPUT_DIR = "dist"
OUTPUT_FILE = os.path.join(OUTPUT_DIR, "sprite_view.py")

HEADER = """# SPDX-FileCopyrightText: 2026 Uwe Jugel
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# WARNING: This file is automatically generated. Do not edit this file directly.
# Edit the respective modules in the sprite_view/ package instead.

import os
import re
import json
import base64
from typing import List
from collections import Counter

import gi
gi.require_version('Notify', '0.7')
gi.require_version('Gtk', '4.0')
gi.require_version('Gdk', '4.0')
gi.require_version('GdkPixbuf', '2.0')
from gi.repository import Nautilus, GObject, Notify, Gtk, Gdk, GdkPixbuf, GLib
"""

def clean_file_content(file_path: str) -> str:
    cleaned_lines = []
    with open(file_path, "r") as f:
        lines = f.readlines()
        
    for line in lines:
        stripped = line.strip()
        # Skip local imports
        if stripped.startswith("from sprite_view"):
            continue
        # Skip headers / SPDX comments
        if stripped.startswith("# SPDX-FileCopyrightText:") or stripped.startswith("# SPDX-License-Identifier:"):
            continue
        # Skip external standard library/GI imports, as they are included globally at the top of the packed file
        if stripped.startswith("import os") or stripped.startswith("import re") or stripped.startswith("import gi") or stripped.startswith("import json") or stripped.startswith("import base64"):
            continue
        if stripped.startswith("gi.require_version") or stripped.startswith("from gi.repository") or stripped.startswith("from typing") or stripped.startswith("from collections"):
            continue
            
        cleaned_lines.append(line)
        
    # Remove leading/trailing empty lines
    content = "".join(cleaned_lines).strip()
    return content + "\n\n"

def pack():
    print("Packing Sprite View application into a single self-contained file...")
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    packed_content = HEADER.strip() + "\n\n"
    
    for file_path in FILES_TO_PACK:
        if not os.path.exists(file_path):
            raise FileNotFoundError(f"Source file not found for packing: {file_path}")
        print(f"  Processing {file_path}...")
        packed_content += f"# --- Begin: {file_path} ---\n"
        packed_content += clean_file_content(file_path)
        packed_content += f"# --- End: {file_path} ---\n\n"
        
    with open(OUTPUT_FILE, "w") as f:
        f.write(packed_content.strip() + "\n")
        
    print(f"✅ Packed application successfully generated at: {OUTPUT_FILE}")

if __name__ == "__main__":
    pack()
